# Generated by Django 4.1 on 2023-02-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
